### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by TigerL06** [Shane-sama/ila3-onboarding#4]
Milestone zu weissen

**Comment by Shane-sama** [comment]
Sie scheinen der deutschen Sprache nicht in vollen Zügen mächtig zu sein. Dies tut mir sehr leid und ich bin mir sicher, dass Sie eine schwere Kindheit hatten. Jedoch kann ich dieses Issue nicht behandeln, da ich Sie höchstwahrscheinlich grammatikalisch falsch verstanden habe.
